### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by selsie** [praecipitator/MakeItemsWeightless#1]
`Compiling
No extra data to consider
("C:\Users\Ranbi\AppData\Local\Temp\Synthesis\2bb878d8-510a-4adb-bb95-00e8a35c3d60\Git\dk41k3v1.n24\Runner\MakeItemsWeightless"): "dotnet" "build \"MakeItemsWeightless.csproj\" --runtime win-x64 -c Release"
Compiled
Sha "1f4417f9850affee45900f5280d876a2bfc113a3"
Running
(""): "dotnet" "run --project \"C:\Users\Ranbi\AppData\Local\Temp\Synthesis\2bb878d8-510a-4adb-bb95-00e8a35c3d60\Git\dk41k3v1.n24\Runner\MakeItemsWeightless\MakeItemsWeightless.csproj\" --runtime win-x64 -c Release --no-build run-patcher --DataFolderPath \"D:\Games\steamapps\common\Skyrim Special Edition\Data\" --ExtraDataFolder \"D:\Skyrim Tools\Synthesis\Data\Skyrim Special Edition\MakeItemsWeightless\" --GameRelease SkyrimSE --ModKey \"Weightless Misc Items.esp\" --LoadOrderFilePath \"C:\Users\Ranbi\AppData\Local\Temp\Synthesis\2bb878d8-510a-4adb-bb95-00e8a35c3d60\Workspace\Weightless Misc Items\Plugins.txt\" --LoadOrderIncludesCreationClub --Localize --OutputPath \"C:\Users\Ranbi\AppData\Local\Temp\Synthesis\2bb878d8-510a-4adb-bb95-00e8a35c3d60\Workspace\Weightless Misc Items\1 - MakeItemsWeightless\Weightless Misc Items.esp\" --PatcherName MakeItemsWeightless --UseUtf8ForEmbeddedStrings"
Mutagen version: 0.39
Mutagen sha: 132e87d3e3c780de96824fa2843f3dd2a6295695
Synthesis version: 0.23.4
Synthesis sha: 203847a2d8bb86e791ceb9246bc1230402f290c5
run-patcher --DataFolderPath "D:\Games\steamapps\common\Skyrim Special Edition\Data" --ExtraDataFolder "D:\Skyrim Tools\Synthesis\Data\Skyrim Special Edition\MakeItemsWeightless" --GameRelease SkyrimSE --ModKey "Weightless Misc Items.esp" --LoadOrderFilePath "C:\Users\Ranbi\AppData\Local\Temp\Synthesis\2bb878d8-510a-4adb-bb95-00e8a35c3d60\Workspace\Weightless Misc Items\Plugins.txt" --LoadOrderIncludesCreationClub --Localize --OutputPath "C:\Users\Ranbi\AppData\Local\Temp\Synthesis\2bb878d8-510a-4adb-bb95-00e8a35c3d60\Workspace\Weightless Misc Items\1 - MakeItemsWeightless\Weightless Misc Items.esp" --PatcherName MakeItemsWeightless --UseUtf8ForEmbeddedStrings
System.ArgumentException: No applicable patchers for Skyrim
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, Nullable`1 exportKey, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 491
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 449
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass36_0.<<InternalRun>b__1>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 412
Synthesis.Bethesda.Execution.CliUnsuccessfulRunException: Error running solution patcher
   at Synthesis.Bethesda.Execution.Patchers.Running.Solution.SolutionPatcherRunner.Run(RunSynthesisPatcher settings, CancellationToken cancel) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Patchers\Running\Solution\SolutionPatcherRunner.cs:line 54
   at Synthesis.Bethesda.Execution.Patchers.Running.Solution.SolutionPatcherRun.Run(RunSynthesisPatcher settings, CancellationToken cancel) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Patchers\Running\Solution\SolutionPatcherRun.cs:line 53
   at Synthesis.Bethesda.Execution.Running.Runner.RunAPatcher.Run(IGroupRun groupRun, PatcherPrepBundle prepBundle, CancellationToken cancellation, Nullable`1 sourcePath, RunParameters runParameters) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Running\Runner\RunAPatcher.cs:line 81
   at Synthesis.Bethesda.Execution.Running.Runner.RunSomePatchers.Run(IGroupRun groupRun, PatcherPrepBundle[] patchers, CancellationToken cancellation, Nullable`1 sourcePath, RunParameters runParameters) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Running\Runner\RunSomePatchers.cs:line 50
   at Synthesis.Bethesda.Execution.Running.Runner.RunAGroup.Run(IGroupRun groupRun, CancellationToken cancellation, DirectoryPath outputDir, RunParameters runParameters, Nullable`1 sourcePath) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Running\Runner\RunAGroup.cs:line 59
   at Synthesis.Bethesda.Execution.Running.Runner.RunAllGroups.Run(IGroupRun[] groups, CancellationToken cancellation, DirectoryPath outputDir, RunParameters runParameters, Nullable`1 sourcePath) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Running\Runner\RunAllGroups.cs:line 36
   at Synthesis.Bethesda.Execution.Running.Runner.ExecuteRun.Run(IGroupRun[] groups, CancellationToken cancellation, DirectoryPath outputDir, RunParameters runParameters, Nullable`1 sourcePath) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Running\Runner\ExecuteRun.cs:line 54
   at Synthesis.Bethesda.GUI.Services.Profile.Running.ExecuteGuiRun.Run(IEnumerable`1 groupRuns, PersistenceMode persistenceMode, Boolean localize, Boolean utf8InEmbeddedStrings, Language targetLanguage, CancellationToken cancel) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.GUI\Services\Profile\Running\ExecuteGuiRun.cs:line 47
   at Synthesis.Bethesda.GUI.ViewModels.Profiles.Running.RunVm.<Run>b__39_1(Unit _) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.GUI\ViewModels\Profiles\Running\RunVm.cs:line 200
`

**Comment by praecipitator** [comment]
Are you trying to run this for Skyrim? This is a Fallout 4 patcher.

**Comment by Noggog** [comment]
> No applicable patchers for Skyrim at ...

Looks like it

Game filters will be out hopefully this weekend, which should help

Dont think there's anything to be done for your patcher.  Just Synth that needs upgrading

**Comment by slacksystem** [comment]
Just for the record, I have the game set to skyrim and it I still was shown this. Might be helpful for others if you mention in your description that it's for fallout specifically

**Comment by Noggog** [comment]
Hmm, I don't see it.  Are you using the most recent UIs?
![image](https://user-images.githubusercontent.com/24981326/213949381-8b7d84db-919d-4962-95b9-d4dc15006eae.png)

**Comment by praecipitator** [comment]
I merged the MR for updating the readme anyway, because why not.
